- name: "[Ubuntu] - update S.O"
  apt: update_cache=yes

- name: "[Ubuntu] - apt-get install"
  apt: name={{ item }} state=present
  with_items:
   - ca-certificates
   - htop
   - python-pip
   - wget
   - apt-transport-https
   - curl
   - wget
   - htop
   - keepalived
  tags: apt-get

- name: "install docker-ce"
  shell: curl -fsSL https://get.docker.com/ | sh

- name: "[Ubuntu] - apt-key - cloud.google.com"
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

- name: "[Ubuntu] - update S.O"
  apt: update_cache=yes

- name: "[Ubuntu] - apt-get install kubernetes"
  apt: name={{ item }} state=present
  with_items:
   - kubelet={{ k8sversionUbuntu }}
   - kubeadm={{ k8sversionUbuntu }}
   - kubectl={{ k8sversionUbuntu }}
